baseURL = "/"
languageCode = "en-us"
title = "Root & Rally"
theme = "kube"
description = "Root & Rally is a community for women's professional sports fans. Find games to attend in your area."
Paginate = 4
ignoreFiles = [ "^logo_main\\.png$" ]
[Params]
  RSSLink = "/index.xml"
  author = "Root & Rally" # add your company name
  email = "myemail@myaddress.xxx"


[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "About"
    weight = -100
    url = "/faq/"
[[menu.main]]
    name = "Schedules"
    weight = -100
    url = "/schedules/"
